<?php

/**
 * Implements hook_ckeditor_plugin().
 */
function ckeditor_a11ychecker_ckeditor_plugin() {
  return array(
    'ckeditor_a11ychecker' => array(
      'name' => 'ckeditor_a11ychecker',
      'desc' => t('CKEditor Accessibility Checker'),
      'path' => '',
      'buttons' => array(
        'a11ychecker' => array(
          'icon' => 'icons/a11ychecker.png',
          'label' => t('Accessibility Checker'),
        ),
      ),
    ),
  );
}

/**
 * Defines the "a11ychecker" plugin.
 *
 * @CKEditorPlugin(
 *   id = "a11ychecker",
 *   label = @Translation("Accessibility Checker")
 * )
 */
class A11yCheckerPlugin extends CKEditorPluginBase {

  /**
   * {@inheritdoc}
   */
  public function getDependencies(Editor $editor) {
    return ['balloonpanel'];
  }

  /**
   * {@inheritdoc}
   */
  public function getLibraries(Editor $editor) {
    return ['core/drupal.jquery'];
  }

  /**
   * {@inheritdoc}
   */
  public function getConfig(Editor $editor) {
    return [];
  }

  /**
   * {@inheritdoc}
   */
  public function getButtons() {
    return array(
      'A11ychecker' => array(
        'label' => t('Accessibility Checker'),
        'image' => base_path() . 'libraries/a11ychecker/icons/a11ychecker.png',
      ),
    );
  }

  /**
   * {@inheritdoc}
   */
  public function getFile() {
    return base_path() . 'libraries/a11ychecker/plugin.js';
  }

}
